### ISSUE TITLE
Alterações no código principal! 

### ISSUE THREAD

**Issue by glaucia86** [AndreSDS/app-weather#1]
Peço que compare os seguintes arquivos com o código do projeto principal:

Link: **[weather.service.ts](https://github.com/glaucia86/livecoding-frontend-projects/blob/master/project-2/weather-app-angular/src/app/weather.service.ts)**

Eu acredito q a sua api não esteja retornando da forma correta. Tenta seguir conforme o meu código e testa se vai retornar esse get no seu código.

**Comment by AndreSDS** [comment]
Oi Glaucia, boa tarde. Eu comparei e a única coisa que fiz de diferente foi a inserção da minha key através do arquivo enviroment.ts , importado na linha 1 e usado na linha 9. De qualquer maneira vou deixar a sintaxe igual ao seu código e testar.
Vou deixar a issue aberta por enquanto.

**Comment by AndreSDS** [comment]
Muito bem eu chequei a forma como eu estava importando a variável de ambiente API_KEY estava correto, porém o valor estava incorreto. Corrigi o valor e agora a chamada get() com todos o parâmetros set(), está retornando valores corretamente. O que eu faço com essa issue, "Close"?

**Comment by glaucia86** [comment]
@AndreSDS fico feliz que você conseguiu resolver o problema. Eu mesmo posso fechar essa issue! Obrigada! :)
